TABLE_CATALOG                                                                                                                    TABLE_SCHEMA                                                                                                                     TABLE_NAME                                                                                                                       TABLE_TYPE
-------------------------------------------------------------------------------------------------------------------------------- -------------------------------------------------------------------------------------------------------------------------------- -------------------------------------------------------------------------------------------------------------------------------- ----------
joe-database                                                                                                                     dbo                                                                                                                              Stores                                                                                                                           BASE TABLE
joe-database                                                                                                                     sys                                                                                                                              database_firewall_rules                                                                                                          VIEW      
joe-database                                                                                                                     dbo                                                                                                                              Users                                                                                                                            BASE TABLE
joe-database                                                                                                                     dbo                                                                                                                              Products                                                                                                                         BASE TABLE
joe-database                                                                                                                     dbo                                                                                                                              Orders                                                                                                                           BASE TABLE
joe-database                                                                                                                     dbo                                                                                                                              Favorites                                                                                                                        BASE TABLE
joe-database                                                                                                                     dbo                                                                                                                              Emails                                                                                                                           BASE TABLE

(7 rows affected)
